### ISSUE TITLE
Codius not running as expected

### ISSUE THREAD

**Issue by jeremysuhw1984** [xrp-community/codius-install#11]
After running the command - wget https://raw.githubusercontent.com/xrp-community/codius-install/master/codius-install.sh -O codius-install.sh && bash codius-install.sh

Selected 2) Check your system for codius errors

[WARN] : It's look like codius is not running as expected ...

[+] Start Debuging ...

........................................
. Checking required installed packages .
........................................

------------------------------------------
PACKAGE              STATUS
------------------------------------------
node                 ✔                    
npm                  ✔                    
hyperd               ✔                    
hyperctl             ✔                    
moneyd               ✔                    
codiusd              ✔                    
certbot              ✔                    

......................................
. Checking required running services .
......................................

------------------------------------------
SERVICE              STATUS
------------------------------------------
hyperd               ✔                    
moneyd               ✔                    
codiusd              ✔                    
nginx                ✔                    

[?] Creating full services log file ?

I'm running on google cloud hosting.

**Comment by N3TC4T** [comment]
Hello @jeremysuhw1984 

did you fixed your issues ?

 if not please rerun the debug command and hit `Y` when you saw `[?] Creating full services log file ?` and then send the output file so we can get more info from your issues .

Thanks

**Comment by jeremysuhw1984** [comment]
Problem is resolved @ codius chat ! Thanks ! Please close this

**Comment by N3TC4T** [comment]
Good to hear :+1:
