### ISSUE TITLE
Moneyd -advanced

### ISSUE THREAD

**Issue by Squixx** [xrp-community/codius-install#14]
I really like your script. works like a charm.

However, i'd like to use it to configure multiple hosts using the same xrp wallet.

This is possible using moneyd 

```
moneyd xrp:configure --advanced
```

(see: https://xrpcommunity.blog/single-wallet-multiple-moneyd-instances/ ) 

Could you integrate the request for giving a unique host name.?

**Comment by N3TC4T** [comment]
Hey 

you don't need to set channel name by yourself anymore for multi moneyd instance 👍 

check out https://github.com/xrp-community/codius-install/issues/5#issuecomment-400476172
