### ISSUE TITLE
certbot error and codiusd not running

### ISSUE THREAD

**Issue by jeremysuhw1984** [xrp-community/codius-install#16]
Hi i run a check on errors and below are the status and errors found. how do i resolve this ? My certificate have not expired yet.
```
[WARN] : It's look like codius is not running as expected ...
[+] Start Debuging ...
........................................
. Checking required installed packages .
........................................
------------------------------------------
PACKAGE              STATUS
------------------------------------------
node                 ✔                    
npm                  ✔                    
hyperd               ✔                    
hyperctl             ✔                    
moneyd               ✔                    
codiusd              ✔                    
certbot              ✘
......................................
. Checking required running services .
......................................
------------------------------------------
SERVICE              STATUS
------------------------------------------
hyperd               ✔                    
moneyd               ✔                    
codiusd              ✘
nginx                ✔    
[?] Creating full services log file ?
[WARN] : With this action all codius services will be restart for debuging

Do you want to continue ? [y/N]: y

[!] Stoping services... 
[!] Execute services and commands in debug mode ... 
[*] This will take some time ...
[!] Killing debug proccess ...
[+] Starting services... 
=============================================================================================================================================
[!] The Debuging Proccess is done .

[-] Please check /tmp/codius_debug-2018-07-12.15-46 for full log output 
```

**Comment by N3TC4T** [comment]
Hey please sent the content of the log file included in `/tmp/codius_debug-2018-07-12.15-46` 

you can use `code` tag for better display

**Comment by jeremysuhw1984** [comment]
How do I retrieve it ? I was prompted permission denied

**Comment by N3TC4T** [comment]
run 

`sudo cat /tmp/codius_debug-2018-07-12.15-46 | nc termbin.com 9999`

in the end it's gives you a link , send it here

**Comment by jeremysuhw1984** [comment]
==================================
node -v ; npm -v ; yarn -v
==================================

v10.6.0
6.1.0
1.7.0

==================================
hyperd run -t test /bin/sh
==================================

time="2018-07-12T15:46:51Z" level=warning msg="devmapper: Usage of
loopback devices is strongly discouraged for production use. Please
use `--storage-opt dm.thinpooldev` or use `man docker` to refer to
dm.thinpooldev section."
time="2018-07-12T15:46:51Z" level=warning msg="devmapper: Base device
already exists and has filesystem xfs on it. User specified filesystem
 will be ignored."
time="2018-07-12T15:46:51Z" level=info msg="[graphdriver] using prior
storage driver "devicemapper""
time="2018-07-12T15:46:51Z" level=info msg="Graph migration to
content-addressability took 0.00 seconds"
time="2018-07-12T15:46:51Z" level=info msg="Firewalld running: true"

==================================
hyperctl info
==================================

Images: 3
Containers: 0
PODs: 0
Storage Driver: devicemapper
  Pool Name: docker-8:1-677388-pool
  Pool Blocksize: 65.54 kB
  Base Device Size: 10.74 GB
  Backing Filesystem: xfs
  Data file: /dev/loop0
  Metadata file: /dev/loop1
  Data Space Used: 1.1 GB
  Data Space Total: 107.4 GB
  Data Space Available: 4.989 GB
  Metadata Space Used: 2.146 MB
  Metadata Space Total: 2.147 GB
  Metadata Space Available: 2.145 GB
  Udev Sync Supported: true
  Deferred Removal Enabled: false
  Deferred Deletion Enabled: false
  Deferred Deleted Device Count: 0
  Data loop file: /var/lib/hyper/devicemapper/devicemapper/data
  Metadata loop file: /var/lib/hyper/devicemapper/devicemapper/metadata
  Library Version: 1.02.146-RHEL7 (2018-01-22)
Hyper Root Dir: /var/lib/hyper
Index Server Address: https://index.docker.io/v1/
Execution Driver:
Total Memory: 3.623 MB
Operating System: CentOS Linux 7 (Core)

==================================
hyperctl list
==================================

POD ID              POD Name            VM name             Status

==================================
moneyd xrp:start
==================================

                                                                           88
                                                                           88
                                                                           88
88,dPYba,,adPYba,   ,adPPYba,  8b,dPPYba,   ,adPPYba, 8b       d8  ,adPPYb,88
88P'   "88"    "8a a8"     "8a 88P'   `"8a a8P_____88 `8b     d8' a8"    `Y88
88      88      88 8b       d8 88       88 8PP"""""""  `8b   d8'  8b       88
88      88      88 "8a,   ,a8" 88       88 "8b,   ,aa   `8b,d8'   "8a,   ,d88
88      88      88  `"YbbdP"'  88       88  `"Ybbd8"'     Y88'     `"8bbdP"Y8
                                                          d8'
                                                         d8'
starting moneyd
2018-07-12T15:47:22.133Z connector:route-broadcaster info generated
random routing secret.
2018-07-12T15:47:22.139Z connector:accounts info add account. accountId=parent
2018-07-12T15:47:22.142Z connector:accounts warn DEPRECATED: plugin
accessed deprecated _log property. accountId=parent
2018-07-12T15:47:22.142Z connector:accounts info add account. accountId=local
2018-07-12T15:47:22.162Z connector:accounts warn DEPRECATED: plugin
accessed deprecated _log property. accountId=local
2018-07-12T15:47:22.162Z connector:accounts warn DEPRECATED: plugin
accessed deprecated _store property. accountId=local
2018-07-12T15:47:22.162Z connector:accounts warn DEPRECATED: plugin
accessed deprecated _store property. accountId=local
(node:22311) UnhandledPromiseRejectionWarning: Error:
{"code":"F00","name":"NotAcceptedError","triggeredAt":"2018-07-12T15:47:23.236Z","data":"cannot
connect to blocked account. reconfigure your uplink to connect with a
new payment channel.","protocolData":[]}
    at Plugin.callback
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.ts:448:20)
    at Plugin.listener
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/eventemitter2/lib/eventemitter2.js:290:17)
    at Plugin.EventEmitter.emit
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/eventemitter2/lib/eventemitter2.js:357:19)
    at Plugin.<anonymous>
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.ts:483:14)
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.js:3:12)
    at Plugin._handleIncomingBtpPacket
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.js:336:16)
    at Plugin.<anonymous>
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.ts:336:18)
(node:22311) UnhandledPromiseRejectionWarning: Unhandled promise
rejection. This error originated either by throwing inside of an async
function without a catch block, or by rejecting a promise which was
not handled with .catch(). (rejection id: 1)
(node:22311) [DEP0018] DeprecationWarning: Unhandled promise
rejections are deprecated. In the future, promise rejections that are
not handled will terminate the Node.js process with a non-zero exit
code.
2018-07-12T15:47:23.559Z connector:app error Error: connection aborted
    at Plugin.once
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.ts:277:21)
    at Plugin.listener
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/eventemitter2/lib/eventemitter2.js:290:17)
    at Plugin.EventEmitter.emit
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/eventemitter2/lib/eventemitter2.js:351:19)
    at Plugin._emitDisconnect
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.ts:539:12)
    at WebSocketReconnector._ws.on
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.ts:270:39)
    at WebSocketReconnector.EventEmitter.emit
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/eventemitter2/lib/eventemitter2.js:351:19)
    at WebSocketReconnector._reconnect
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/ws-reconnect.ts:58:10)
    at WebSocket._instance.on
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/ws-reconnect.ts:34:71)
    at WebSocket.emit (events.js:182:13)
    at WebSocket.emitClose
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/node_modules/ws/lib/WebSocket.js:211:10)
(node:22311) UnhandledPromiseRejectionWarning: Error:
{"code":"F00","name":"NotAcceptedError","triggeredAt":"2018-07-12T15:47:29.311Z","data":"cannot
connect to blocked account. reconfigure your uplink to connect with a
new payment channel.","protocolData":[]}
    at Plugin.callback
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.ts:448:20)
    at Plugin.listener
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/eventemitter2/lib/eventemitter2.js:290:17)
    at Plugin.EventEmitter.emit
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/eventemitter2/lib/eventemitter2.js:357:19)
    at Plugin.<anonymous>
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.ts:483:14)
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.js:3:12)
    at Plugin._handleIncomingBtpPacket
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.js:336:16)
    at Plugin.<anonymous>
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.ts:336:18)
(node:22311) UnhandledPromiseRejectionWarning: Unhandled promise
rejection. This error originated either by throwing inside of an async
function without a catch block, or by rejecting a promise which was
not handled with .catch(). (rejection id: 2)

==================================
moneyd xrp:info
==================================

fetching channels...
connecting to xrp ledger...
account: r3QRXAy2YqoZ8su8E8kzPJgyRWLnoxqnEZ
balance: 166.942231 XRP
index  destination                         amount (drops)  balance
(drops)  expiry
0      rK6g2UYc4GpQH8DYdPG7wywyQbxkJpQTTN  10000000        60000

(node:22311) UnhandledPromiseRejectionWarning: Error:
{"code":"F00","name":"NotAcceptedError","triggeredAt":"2018-07-12T15:47:35.374Z","data":"cannot
connect to blocked account. reconfigure your uplink to connect with a
new payment channel.","protocolData":[]}
    at Plugin.callback
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.ts:448:20)
    at Plugin.listener
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/eventemitter2/lib/eventemitter2.js:290:17)
    at Plugin.EventEmitter.emit
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/eventemitter2/lib/eventemitter2.js:357:19)
    at Plugin.<anonymous>
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.ts:483:14)
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.js:3:12)
    at Plugin._handleIncomingBtpPacket
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.js:336:16)
    at Plugin.<anonymous>
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.ts:336:18)
(node:22311) UnhandledPromiseRejectionWarning: Unhandled promise
rejection. This error originated either by throwing inside of an async
function without a catch block, or by rejecting a promise which was
not handled with .catch(). (rejection id: 3)

==================================
codiusd
==================================

(node:22311) UnhandledPromiseRejectionWarning: Error:
{"code":"F00","name":"NotAcceptedError","triggeredAt":"2018-07-12T15:47:41.446Z","data":"cannot
connect to blocked account. reconfigure your uplink to connect with a
new payment channel.","protocolData":[]}
    at Plugin.callback
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.ts:448:20)
    at Plugin.listener
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/eventemitter2/lib/eventemitter2.js:290:17)
    at Plugin.EventEmitter.emit
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/eventemitter2/lib/eventemitter2.js:357:19)
    at Plugin.<anonymous>
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.ts:483:14)
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.js:3:12)
    at Plugin._handleIncomingBtpPacket
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.js:336:16)
    at Plugin.<anonymous>
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.ts:336:18)
(node:22311) UnhandledPromiseRejectionWarning: Unhandled promise
rejection. This error originated either by throwing inside of an async
function without a catch block, or by rejecting a promise which was
not handled with .catch(). (rejection id: 4)
2018-07-12T15:47:41.709Z codiusd:App info starting codiusd...
(node:22311) UnhandledPromiseRejectionWarning: Error:
{"code":"F00","name":"NotAcceptedError","triggeredAt":"2018-07-12T15:47:47.515Z","data":"cannot
connect to blocked account. reconfigure your uplink to connect with a
new payment channel.","protocolData":[]}
    at Plugin.callback
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.ts:448:20)
    at Plugin.listener
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/eventemitter2/lib/eventemitter2.js:290:17)
    at Plugin.EventEmitter.emit
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/eventemitter2/lib/eventemitter2.js:357:19)
    at Plugin.<anonymous>
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.ts:483:14)
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.js:3:12)
    at Plugin._handleIncomingBtpPacket
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.js:336:16)
    at Plugin.<anonymous>
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.ts:336:18)
(node:22311) UnhandledPromiseRejectionWarning: Unhandled promise
rejection. This error originated either by throwing inside of an async
function without a catch block, or by rejecting a promise which was
not handled with .catch(). (rejection id: 5)

==================================
netstat -tulpn
==================================

Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address
State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*
LISTEN      1099/sshd
tcp        0      0 127.0.0.1:25            0.0.0.0:*
LISTEN      1109/master
tcp6       0      0 :::22                   :::*
LISTEN      1099/sshd
tcp6       0      0 ::1:25                  :::*
LISTEN      1109/master
udp        0      0 127.0.0.1:323           0.0.0.0:*
         322/chronyd
udp        0      0 0.0.0.0:68              0.0.0.0:*
         573/dhclient
udp6       0      0 ::1:323                 :::*
         322/chronyd
(node:22311) UnhandledPromiseRejectionWarning: Error:
{"code":"F00","name":"NotAcceptedError","triggeredAt":"2018-07-12T15:47:53.583Z","data":"cannot
connect to blocked account. reconfigure your uplink to connect with a
new payment channel.","protocolData":[]}
    at Plugin.callback
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.ts:448:20)
    at Plugin.listener
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/eventemitter2/lib/eventemitter2.js:290:17)
    at Plugin.EventEmitter.emit
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/eventemitter2/lib/eventemitter2.js:357:19)
    at Plugin.<anonymous>
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.ts:483:14)
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.js:3:12)
    at Plugin._handleIncomingBtpPacket
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.js:336:16)
    at Plugin.<anonymous>
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.ts:336:18)
(node:22311) UnhandledPromiseRejectionWarning: Unhandled promise
rejection. This error originated either by throwing inside of an async
function without a catch block, or by rejecting a promise which was
not handled with .catch(). (rejection id: 6)
(node:22311) UnhandledPromiseRejectionWarning: Error:
{"code":"F00","name":"NotAcceptedError","triggeredAt":"2018-07-12T15:47:59.654Z","data":"cannot
connect to blocked account. reconfigure your uplink to connect with a
new payment channel.","protocolData":[]}
    at Plugin.callback
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.ts:448:20)
    at Plugin.listener
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/eventemitter2/lib/eventemitter2.js:290:17)
    at Plugin.EventEmitter.emit
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/eventemitter2/lib/eventemitter2.js:357:19)
    at Plugin.<anonymous>
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.ts:483:14)
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.js:7:71
    at new Promise (<anonymous>)
    at __awaiter
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.js:3:12)
    at Plugin._handleIncomingBtpPacket
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.js:336:16)
    at Plugin.<anonymous>
(/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-btp/src/index.ts:336:18)
(node:22311) UnhandledPromiseRejectionWarning: Unhandled promise
rejection. This error originated either by throwing inside of an async
function without a catch block, or by rejecting a promise which was
not handled with .catch(). (rejection id: 7)
codius-install.sh: line 992: 22311 Killed                  bash -c
'moneyd xrp:start'
codius-install.sh: line 992: 22358 Killed                  bash -c 'codiusd'
codius-install.sh: line 992: 22178 Killed                  bash -c
'hyperd run -t test /bin/sh'

**Comment by N3TC4T** [comment]
It's look like there is a problem with moneyd 

1. Stop all services 

```
systemctl stop nginx moneyd-xrp codiusd hyperd
```

2. cleanup channel by running

```
moneyd xrp:cleanup
```

3. remove `~/.moneyd.json` file

```
rm ~/.moneyd.json
```

4. reconfigure moneyd by running 

```
moneyd xrp:configure
```

5.  start all services again 

```
systemctl restart nginx moneyd-xrp codiusd hyperd
```

also if this step dosen't help please post status of codiusd service as well 

```
systemctl status codiusd -l
```

good luck

**Comment by jonaagenilsen** [comment]
Check hostname on your shell. It should be identical to actual Codius-hostname. If they are, "[WARN] : It's look like codius is not running as expected ..." wll go away

hostnamectl set-hostname Your-Host-Name-Here

**Comment by jeremysuhw1984** [comment]
Hi

Problem can only resolve doing a fresh install.

 Now codius server is running fine now version 1.1.3
