### ISSUE TITLE
Needs a new hyper-bootstrap script

### ISSUE THREAD

**Issue by spearl** [xrp-community/codius-install#2]
This is very awesome! Thank you for putting this up.

Unfortunately, the version of hyper for Ubuntu that is installed by the bootstrap script is out of date and the port mapping is broken. We're building our own version for CentOS 7 which is the only OS we currently support.
However, I just opened an issue to create hyper builds for other OSes (https://github.com/codius/codiusd/issues/61) so once this is done and a new bootstrap script is put up you'll only have to change that url and it will install the right version!

**Comment by N3TC4T** [comment]
Oh I see, Thanks , So I'm removing the other distros supports from the script until finding a solution for this .

**Comment by spearl** [comment]
Just closed the other issue. Just built new packages for Centos, Fedora, Debian and Ubuntu and the new bootstrap script pointing to them is located at `https://codius-hyper-install.s3.amazonaws.com/hyper-bootstrap.sh`

Update the hyper bootstrap URL and give it a try if you want and we can close this!

**Comment by N3TC4T** [comment]
thanks , you are awesome   :+1: 

also there is an error in debian base system in running hyperd because of lack `aufs` lib 

`couldn't run auplink before unmount exec: "auplink": executable file not found in $path`

that can be fix buy installing `aufs-tools` package .

Just saying
