### ISSUE TITLE
Cleanup codius from this server gives errors.

### ISSUE THREAD

**Issue by GaetanoH** [xrp-community/codius-install#23]
**Describe the issues**
Whenever I run the cleanup of codius from my server I get an issue 
`WARN] : Thie action will remove packages listed below and all config files belong to them :
  
* Codiusd
* Moneyd
* Hyperd
* Certbot
* Nginx
* Nodejs (npm & yarn)

Continue Anyway ? [y/N]: y
yarn global v1.7.0
[1/4] Removing module moneyd...
error This module isn't specified in a manifest.
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.`

**To Reproduce**
1. run the script 
2. enter num `4` and hit ENTER

**Expected behavior**
The codius host should be cleared and reset.

**Comment by SneakyFish5** [comment]
Did you install your moneyd, codiusd, and other packages via npm or yarn? Or was your host installed via script or medium blog guide?

I think the problem is that you installed via npm but script tries to remove with yarn first. I'll see if I can open a PR to fix that.

**Comment by N3TC4T** [comment]
Actually this is not an error , it's just say the packages is not installed with `YARN` and will be removed with `NPM` in next line
