### ISSUE TITLE
Script misses firewall & setsebool

### ISSUE THREAD

**Issue by cointrek** [xrp-community/codius-install#26]
**Describe the issues**
Add 

**To Reproduce**
You can run the script to completion and note that the commands have not been executed.

**Expected behavior**
Add:
setsebool -P httpd_can_network_connect 1
yum install firewalld
systemctl start firewalld
firewall-cmd --zone=public --add-port=443/tcp --permanent 
firewall-cmd --zone=public --add-port=7768/tcp --permanent
firewall-cmd --reload

**Screenshots**
N/A

**Comment by SneakyFish5** [comment]
The script does those things except it doesn't install firewalld, just runs the `firewall-cmd --zone=public --add-port=443/tcp --permanent` in case firewalld is installed. As for `firewall-cmd --zone=public --add-port=7768/tcp --permanent`, I recommend you don't do this as that's opening up your moneyd account port to the public. You should be fine without it.

**Comment by SneakyFish5** [comment]
Actually you're right, there is one thing that is missing. `firewall-cmd --reload` is missing, my bad. I will open a PR to address this.

**Comment by cointrek** [comment]
Sweet! Happy to contribute. And, thanks.
