### ISSUE TITLE
Checking required running services - codiusd comes back with red "x" but systemctl status is green

### ISSUE THREAD

**Issue by fubar2208** [xrp-community/codius-install#28]
First off, i'm super green and don't know much....thank you so much for making this thing...it is incredibly useful and I've shared it more than once.

ok....

I'm Running option 2 - Check your system for codius errors

on the second check "Checking required running services" - codiusd comes back with a red "x".

when i run all the systemctl status commands...everything comes back green and running.

What am I missing here? 

Appreciate any help.

Thanks,

FUBS

**Comment by N3TC4T** [comment]
Thanks 

just fixed the issues

**Comment by fubar2208** [comment]
do i need to re-install or anything?
