### ISSUE TITLE
Error in codius.conf prevents passing Self Test

### ISSUE THREAD

**Issue by magicbox2004** [xrp-community/codius-install#30]
In /etc/nginx/conf.d/codius.conf

Some proxy fields under "Location" are in an incorrect order. This is preventing the enabling of Websocket support and thus causing the host to fail self test.

The correct order should be:

location / {
      proxy_pass http://127.0.0.1:3000;
      **proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_buffering  off;**
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $remote_addr;

This is described here:  https://medium.com/codius/codiusd-1-2-0-upgrading-and-websocket-support-42f712a0cee9 where it is stated that the order of the proxy fields matters. The bolded fields must come first.

**Comment by N3TC4T** [comment]
Thanks Fixed
