### ISSUE TITLE
Replace "moneyd xrp: configure" to "moneyd xrp: configure --advanced" ?

### ISSUE THREAD

**Issue by marketarea** [xrp-community/codius-install#5]
Thinking out loud ).
Perhaps it would be better if you replace:
"moneyd xrp: configure" to "moneyd xrp: configure --advanced"?

https://xrpcommunity.blog/single-wallet-multiple-moneyd-instances/

**Comment by detlevhinkel** [comment]
agreed

**Comment by N3TC4T** [comment]
as `moneyd xrp: configure --advanced` is an intractive command and need to enter about 4 item by user and this cannot be done by bash , maybe generating an basic `.moneyd.json` file with a simple configure command and changing the `channel name` or other items would be possible .

**Comment by N3TC4T** [comment]
As the https://github.com/interledgerjs/moneyd-uplink-xrp/pull/6 patch the moneyd channel have a random 32 char name by default now ,  so I think that's would be enough for preventing multi moneyd instance issues . 

aslo if you won't update your moneyd-uplink-xrp to v1.1.2 then check lines below :

https://github.com/xrp-community/codius-install/blob/321e7b1571ab95b0c1382f0374ab05ba48908578/codius-install.sh#L460-L461
