### ISSUE TITLE
Feature Request: 7th option, update Codiusd, Moneyd, and hyperd

### ISSUE THREAD

**Issue by SneakyFish5** [xrp-community/codius-install#7]
Would be nice to have an option to check for updates to all three programs and then update them if a new update is out. You don’t even have to make it check, you can just run the commands to update them as part of the option. 

Just a lot easier to update if it’s all automated in an option. Something to think about, but if it’s not possible that’s cool. Thanks :)

**Comment by N3TC4T** [comment]
Added :+1:

**Comment by SneakyFish5** [comment]
Wow that was fast, thanks
